[package]
name = "mitsein"
version = "0.1.1"
authors = ["Sean Olson <olson.sean.k@gmail.com>"]
description = "Strongly typed APIs for non-empty collections and views."
repository = "https://github.com/olson-sean-k/mitsein"
readme = "README.md"
edition = "2021"
rust-version = "1.75.0"
license = "MIT"
keywords = [
    "collection",
    "non-empty",
    "one-or-more",
    "vector"
]
categories = ["data-structures"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs"
]

[features]
default = ["alloc"]
alloc = ["itertools/use_alloc", "serde/alloc"]
itertools = ["dep:itertools"]
serde = ["dep:serde", "dep:serde_derive"]

[dependencies]

[dependencies.itertools]
version = "^0.13.0"
default-features = false
optional = true

[dependencies.serde]
version = "1.0"
default-features = false
optional = true

[dependencies.serde_derive]
version = "1.0"
default-features = false
optional = true
